// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdSG6QigGK7Hi5PVXlmcAWrtff63fhnB0',
    appId: '1:918824101309:web:c31ddef93f0fb768269ed4',
    messagingSenderId: '918824101309',
    projectId: 'wolfpackapp-7f5ca',
    authDomain: 'wolfpackapp-7f5ca.firebaseapp.com',
    storageBucket: 'wolfpackapp-7f5ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgkVs37qTaPxfgBtgdvzSacGqyvSomiA',
    appId: '1:918824101309:android:3d26bebad19c0f29269ed4',
    messagingSenderId: '918824101309',
    projectId: 'wolfpackapp-7f5ca',
    storageBucket: 'wolfpackapp-7f5ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4nvx1Hr7TsJGH8D7S_ChrP_uKPIegpg8',
    appId: '1:918824101309:ios:a243c04dee854426269ed4',
    messagingSenderId: '918824101309',
    projectId: 'wolfpackapp-7f5ca',
    storageBucket: 'wolfpackapp-7f5ca.appspot.com',
    iosBundleId: 'com.example.wolfPackTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4nvx1Hr7TsJGH8D7S_ChrP_uKPIegpg8',
    appId: '1:918824101309:ios:a243c04dee854426269ed4',
    messagingSenderId: '918824101309',
    projectId: 'wolfpackapp-7f5ca',
    storageBucket: 'wolfpackapp-7f5ca.appspot.com',
    iosBundleId: 'com.example.wolfPackTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdSG6QigGK7Hi5PVXlmcAWrtff63fhnB0',
    appId: '1:918824101309:web:39655e87e7717443269ed4',
    messagingSenderId: '918824101309',
    projectId: 'wolfpackapp-7f5ca',
    authDomain: 'wolfpackapp-7f5ca.firebaseapp.com',
    storageBucket: 'wolfpackapp-7f5ca.appspot.com',
  );
}
